### ISSUE TITLE
rpg being bugged and unable to open up the gui, all part of item have been taken out prior this bug

### ISSUE THREAD

**Issue by itzhenryzz** [nnichael/MOGL#185]

**Comment by nnichael** [comment]
```
[22:34:25 ERROR]: Could not pass event PlayerInteractEvent to roleplay-gradle v1.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getType()" because "inventory" is null
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftContainer.getNotchInventoryType(CraftContainer.java:92) ~[paper-1.19.2.jar:git-Paper-219]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:335) ~[paper-1.19.2.jar:git-Paper-219]
        at com.Michael.roleplay.weapons.WeaponsManager.openRangedWeaponInventory(WeaponsManager.java:2084) ~[RolePlay-1.0.0-SNAPSHOT.jar:?]
        at com.Michael.roleplay.weapons.WeaponsListener.onClickRangedWeapon(WeaponsListener.java:415) ~[RolePlay-1.0.0-SNAPSHOT.jar:?]
```
